import Head from 'next/head'
import Feed from '../../components/Feed'
import Sidebar from '../../components/Sidebar'
import Widgets from '../../components/Widgets'
import styles from '../styles/Home.module.css'

export default function Home({newsResults}) {
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Twitter-logo.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar/>
        <Feed />
        <Widgets newsResults={newsResults}/>
      </main>
    </>
  )
}


export async function getServerSideProps() {
  const res = await fetch(
    `https://saurav.tech/NewsAPI/top-headlines/category/technology/in.json`
  );
  const newsResults = await res.json();
  return {
    props: {
      newsResults: newsResults.articles,
    },
  };
}