import { getServerSession } from "next-auth";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useContext } from "react";
import { AuthBottomBar } from "../../components/AuthBottomBar";
import Feed from "../../components/Feed";
import Modal from "../../components/Modal";
import Sidebar from "../../components/Sidebar";
import Widgets from "../../components/Widgets";
import styles from "../styles/Home.module.css";
import { authOptions } from "./api/auth/[...nextauth]";
import { ModalContext } from "./_app";

export default function Home({ postResults, likedResults }) {
  const { modalState } = useContext(ModalContext);
  const { data: session } = useSession();
  return (
    <>
      <Head>
        <title>Twitter</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Twitter-logo.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />
        <Feed posts={postResults} liked={likedResults} />
        <Widgets />
        {modalState.state && <Modal />}
        {!session && <AuthBottomBar />}
      </main>
    </>
  );
}

export async function getServerSideProps(context) {
  const session = await getServerSession(context.req, context.res, authOptions);
  let likedResults;
  if (session.user) {
    const userID = session.user.id;
    const likedPostsResponse = await fetch(
      `http://localhost:3000/api/users/${userID}/liked`
    );
    likedResults = await likedPostsResponse.json();
  }
  const posts = await fetch("http://localhost:3000/api/posts/");
  const data = await posts.json();
  return {
    props: {
      postResults: data.posts,
      likedResults: likedResults?.data,
    },
  };
}
